services:
  routingcontainer:
    class:    api_routingcontainer
    arguments: [@routing]
    shared:   false
  routing:
    class:    api_routing
    arguments:
      dispatcher: @sfEventDispatcher
      request: @request
    shared:   true
  request:
    class:    api_request
    arguments:
      lang:
        default: de
        acceptBrowserLang: false
        languages: [en,de,fr,it]
      extensions:
        default: html
        allowed: [html, json, js]
    shared:   true
  response:
    class:    api_response
    shared:   true
  response_exception:
    class:    api_response_exception
    arguments: [@api_views_default]
    shared:   true
  response_withview:
    class:    api_response_withview
    arguments: [@api_views_default]
    shared:   true
  i18n:
    class:    api_i18n_dispatcher
    arguments: []
    shared:   true
  db:
    class:    XXX
    arguments:
      dsn:
        host: localhost
        username: root
        password:
        dbname: XXX
    shared:   true
  auth:
    class:    api_pam_auth_XXX
    arguments:
        opts:
          class: XXX
        request: @request
        db: @db
    shared:   true
  perm:
    class:    api_pam_perm_XXX
    arguments:
        opts:
          class: crud
        response: @response
    shared:   true
  pam:
    class:    api_pam
    arguments: [@auth, @perm]
    shared:   true
  controller:
    class:    api_controller
    arguments:
      request: @request
      routing: @routing
      filters:
        request:
#          api_filter_XXX: ~
        response:
#          api_filter_XXX: ~
    shared:   true
  html:
    class:    api_views_html
    arguments: [@routing, @request, @response]
    shared:   false
  json:
    class:    api_views_json 
    arguments: [@routing, @request, @response]
    shared:   false
  api_views_default:
    class:    api_views_default
    arguments: [@routing, @request, @response, @i18n]
    shared:   true
  api_command_default:
    class:    api_command_default
    arguments: [@routing, @request, @response]
    shared:   true
  sfEventDispatcher:
    class:    sfEventDispatcher
    shared:   true
  sfRequestHandler:
    class:    sfRequestHandler
    arguments: [@sfEventDispatcher]
    shared:   true
